[package]
name = "socket"
version = "0.1.0"
authors = ["Alan Hoffmeister <alanhoffmeister@gmail.com>"]

[dependencies]
tokio = "0.1.6"
actix = "0.5.7"
futures = "0.2.1"
tokio-io = "0.1.6"
bytes = "0.4.7"
